In [1]:
import numpy as np
x = [1, 2]
type(x)

list

In [4]:
y = np.array([1, 2])
type(y)

numpy.ndarray

* 建立一維或多維的 Numpy 陣列

In [9]:
# 等距的整數陣列
np1 = np.arange(0, 11, 2)
np1

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np2 = np.arange(1, 101 ,1)
np2

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [14]:
# 設定範圍的等距陣列 => 等差數列
np3 = np.linspace(1, 9 ,3)
np3

array([1., 5., 9.])

In [16]:
np4 = np.linspace(1, 230, 57)
np4

array([  1.        ,   5.08928571,   9.17857143,  13.26785714,
        17.35714286,  21.44642857,  25.53571429,  29.625     ,
        33.71428571,  37.80357143,  41.89285714,  45.98214286,
        50.07142857,  54.16071429,  58.25      ,  62.33928571,
        66.42857143,  70.51785714,  74.60714286,  78.69642857,
        82.78571429,  86.875     ,  90.96428571,  95.05357143,
        99.14285714, 103.23214286, 107.32142857, 111.41071429,
       115.5       , 119.58928571, 123.67857143, 127.76785714,
       131.85714286, 135.94642857, 140.03571429, 144.125     ,
       148.21428571, 152.30357143, 156.39285714, 160.48214286,
       164.57142857, 168.66071429, 172.75      , 176.83928571,
       180.92857143, 185.01785714, 189.10714286, 193.19642857,
       197.28571429, 201.375     , 205.46428571, 209.55357143,
       213.64285714, 217.73214286, 221.82142857, 225.91071429,
       230.        ])

In [21]:
np5 = np.ones((5,))
# np5 = np.ones([5,])
np5

array([1., 1., 1., 1., 1.])

In [24]:
np6 = np.ones((2, 3))
# np6 = np.ones([2, 3])
np6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
listdata = [[1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15]]
np7 = np.array(listdata)
np7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
# 顯示維度
np7.ndim

2

In [27]:
# 顯示維度形狀
np7.shape

(3, 5)

In [28]:
# 元素數量
np7.size

15