* 改變陣列形狀 - reshape()

In [2]:
import numpy as np
adata = np.arange(1, 17)
adata

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
bdata = adata.reshape(4, 4)
bdata

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
cdata = adata.reshape(8, 2)
cdata

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

* 陣列取值 - 一維陣列

In [7]:
na = np.arange(0, 6)
na

array([0, 1, 2, 3, 4, 5])

In [10]:
na[3]

3

In [11]:
na[1:4]

array([1, 2, 3])

In [12]:
na[1:4:2]

array([1, 3])

* 陣列取值 - 二維陣列

In [14]:
na = np.arange(1, 17).reshape(4, 4)
na

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
na[2, 3]

12

In [16]:
na[1, 1:3]

array([6, 7])

In [17]:
na[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [20]:
# na[0:3:2, 0:3:2]
na[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

* 產生隨機的陣列資料

In [21]:
np.random.rand(2, 3)

array([[0.32484912, 0.04947732, 0.17380096],
       [0.4552497 , 0.8925367 , 0.60100331]])

In [22]:
np.random.randn(2, 3)

array([[ 0.39639235,  0.40307784, -0.78704532],
       [-1.34025618, -0.66669374,  0.23199644]])

In [23]:
np.random.randint(5)

2

In [24]:
np.random.choice(10, 5, replace=False)

array([5, 8, 9, 7, 4])

* 陣列運算

In [25]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3 ,3)

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
a + b

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [30]:
a < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

* 常用的計算與統計函數

In [31]:
a = np.arange(1, 13).reshape(3 ,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [33]:
np.min(a, axis=1)

array([1, 5, 9])

In [35]:
np.mean(a)

6.5

In [38]:
np.std(a)

3.452052529534663

* numpy 排序

In [39]:
a = np.random.choice(50, 10, replace=False)
a

array([15, 33,  6,  3,  0, 47, 29, 25, 28,  7])

In [43]:
# 對陣列中的值進行排序並將結果返回
np.sort(a)

array([ 0,  3,  6,  7, 15, 25, 28, 29, 33, 47])

In [44]:
# 對陣列中的值進行排序並將索引返回
np.argsort(a)

array([4, 3, 2, 9, 0, 7, 8, 6, 1, 5], dtype=int64)